# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.17.6-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN go build -o=./bin/api ./cmd/api

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /app/bin/api /bin/api

EXPOSE 4000

USER nonroot:nonroot

CMD [ "-db-dsn=postgres://greenlight:greenlight@localhost/greenlight" ]

ENTRYPOINT [ "/bin/api" ]