# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.17.6-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN go build -o=./bin/api ./cmd/api

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /app/cmd/api /greenlight

EXPOSE 4000

USER nonroot:nonroot

ENTRYPOINT [ "/greenlight" ]